### ISSUE TITLE
Does not work after install

### ISSUE THREAD

**Issue by gabriele-h** [mehmetc/primo-explore-dom#1]
Hi Mehmet,

I tried installing primo-explore-dom in my primo-explore-devenv. If I do npm ls it is listed as well as it is included in package.json.

But when I do a gulp run with my view, then in the browser angular.reloadWithDebugInfo(); and Primo.isDebugEnabled(), I get "ReferenceError: Primo is not defined" in the console.

I tried finding out whether more configuration was necessary for the package to be included when running gulp, but couldn't find a solution so far.

Best,
Gabriele

**Comment by mehmetc** [comment]
This is interesting. Do you have time to walk through this together? (Skype/Hangouts/...)

**Comment by gabriele-h** [comment]
Yes, I will get in contact with you via e-mail!

**Comment by mehmetc** [comment]
Thank you Gabriele. I updated the documentation. Hopefully it's clearer now.
