### ISSUE TITLE
user.isOnCampus() returns false after login?

### ISSUE THREAD

**Issue by jhercher** [mehmetc/primo-explore-dom#3]
Hi @mehmetc ,

user.isOnCampus() works fine for me if I'm not logged in:

<img width="1384" alt="onCampus_notLoggedIn
" src="https://user-images.githubusercontent.com/941635/92239477-604a5280-eebb-11ea-9ac5-b9cc12ca919e.png">

However, if I do login the Promise returns false, which is wrong:

<img width="1394" alt="onCampus_loggedIn" src="https://user-images.githubusercontent.com/941635/92239709-be773580-eebb-11ea-9ab6-e03ebcc5e556.png">

I'm not sure if I've done something wrong with the installation? Can you help me out? 

Best,
Johannes

**Comment by mehmetc** [comment]
Interesting. Just to be sure you are on campus, right? Physically or using a VPN. I'm using the JWT token to determine if someone is on campus. 
```Primo.explore.helper.jwtData()```

It might be that your VPN is not sending everything through the university network. I have to use EzProxy if I want that.

Mehmet

**Comment by jhercher** [comment]
Hi @mehmetc,  


I checked this being physically on the campus as well, so I don't think the VPN is the culprit here. 
Thank you for the tip with Primo.explore.helper.jwtData(). I can see that the IP is blanked out after login, which might be the reason for the wrong data in the onCampus property [(see attachment)](https://github.com/mehmetc/primo-explore-dom/files/5319241/JWT_OnCampus_error.txt). I've send a case to ExLibris (00886167).

Any ideas are welcome ;)

cheers, 
Johannes
